### ISSUE TITLE
Addon not working

### ISSUE THREAD

**Issue by borodag** [moromete/plugin.video.digionline#1]
Ho

Sadly this admin doesn't work.

**Comment by moromete** [comment]
Is working just fine. You need digionline account and to be in RO networks.
If still not working any issue need some debug information not just to say "is not working". Kodi has log files ....

**Comment by borodag** [comment]
[kodi.log](https://github.com/moromete/plugin.video.digionline/files/4353880/kodi.log)
Multumesc.

**Comment by borodag** [comment]
Cand doresc sa accesez un canal nu se incarca si revine la meniul cu canale.

În joi, 19 mar. 2020 la 11:30, moromete <notifications@github.com> a scris:
