### ISSUE TITLE
Addonul nu functioneaza

### ISSUE THREAD

**Issue by borodag** [moromete/plugin.video.digionline#2]
Salut.

Cand doresc sa-l deschid nu pornesc like-urile.

Am atasat log.
[kodi (1).log](https://github.com/moromete/plugin.video.digionline/files/4354456/kodi.1.log)

**Comment by borodag** [comment]
[kodi (2).log](https://github.com/moromete/plugin.video.digionline/files/4358184/kodi.2.log)
Clean install

**Comment by moromete** [comment]
Pe ce provider de internet esti conecta? Din ce vad serverul de la rds raspunde cu 401 Unauthorized. Daca te conectezi direct pe https://www.digionline.ro functioneaza ?

**Comment by borodag** [comment]
Rds.
Da , functioneaza aplicația pe mobil , conectată la wifi rețea RDS dar e posibil acele link -uri sa se fi schimbat. Aplicația digi online a lor,   in versiunea sa veche, nu mai functioneaza.

**Comment by moromete** [comment]
link-urile nu au cum sa expire deoarece sunt preluate direct de pe site-ul lor in real time. 
ce versiune de addon folosesti? e instalata manual (zip) sau din repository (moromete repo) ?
Incearaca in setarile addon-ului sa bifezi optiunea "reset login".

**Comment by borodag** [comment]
Salut. Folosesc 0.1.1 din repo. Am incercat acum cu reset login și comportamentul e acelasi.
![20200322_131404](https://user-images.githubusercontent.com/61414504/77248044-218f4b80-6c3f-11ea-9d35-bda6b5c4e215.jpg)
![20200322_131352](https://user-images.githubusercontent.com/61414504/77248046-22c07880-6c3f-11ea-927f-c4a18ed353c0.jpg)
![20200322_131416](https://user-images.githubusercontent.com/61414504/77248048-23590f00-6c3f-11ea-9fab-ca4c1cd0d142.jpg)

**Comment by moromete** [comment]
Pe ce sistem de operare e instalat si ce versiune de kodi? O sa incerc si eu pe un windows. Pana acum il am pus pe un opensuse 15.1 cu kodi 18. si pe un raspbery pi cu libreelec si functioneza perfect .

**Comment by borodag** [comment]
Android 8.0.0 , Leia 18.6 , Mibox3 . Pe acest aparat ajung pana in meniu dar nu porneste video.
Am incercat acum și pe Samsung Galaxy S8 și nu am reusit sa-l pornesc deloc(nu intra in meniu)
[kodi-samsung.log](https://github.com/moromete/plugin.video.digionline/files/4368301/kodi-samsung.log)

**Comment by moromete** [comment]
Se pare ca pentru samsung folderul asta nu exista "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.digionline/" si nu poate sa salveze cookie-ul de login. Acel folder ar trebui sa se creeze automat in momentul in care in setari pui datele de login (username si parola digionline). Deocamdata nu am un device cu android si kodi sa testez. O sa verific cand reusesc sa pun mana pe unul.

**Comment by borodag** [comment]
Am gasit acel folder dar eroarea persistă. E posibil să fie necesară setarea unui drept de scriere.


![Screenshot_20200324-110444_ES File Explorer](https://user-images.githubusercontent.com/61414504/77407823-6fcb5880-6dbf-11ea-9d29-98dee33fad1c.jpg)

**Comment by borodag** [comment]
Totusi , restul plugin-urilor functioneaza corect. Lasa-mi un mesaj daca afli ceva.

Multumesc , o zi buna .

**Comment by moromete** [comment]
Fixed on 0.1.3 tested on vim3L, android 9, kodi 18.
